[2021-11-19 10:41:48,992] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Collection_resport.get_excel scheduled__2021-11-18T00:00:00+00:00 [queued]>
[2021-11-19 10:41:49,028] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Collection_resport.get_excel scheduled__2021-11-18T00:00:00+00:00 [queued]>
[2021-11-19 10:41:49,028] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 10:41:49,028] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-19 10:41:49,028] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 10:41:49,065] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_excel> on 2021-11-18 00:00:00+00:00
[2021-11-19 10:41:49,078] {standard_task_runner.py:52} INFO - Started process 12951 to run task
[2021-11-19 10:41:49,085] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Collection_resport', 'get_excel', 'scheduled__2021-11-18T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/collection.py', '--cfg-path', '/tmp/tmptr4s9mja', '--error-file', '/tmp/tmp7k_kp3_a']
[2021-11-19 10:41:49,097] {standard_task_runner.py:77} INFO - Job 70: Subtask get_excel
[2021-11-19 10:41:49,190] {logging_mixin.py:109} INFO - Running <TaskInstance: Collection_resport.get_excel scheduled__2021-11-18T00:00:00+00:00 [running]> on host user-Latitude-3410
[2021-11-19 10:41:49,272] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=shindesushant818@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Collection_resport
AIRFLOW_CTX_TASK_ID=get_excel
AIRFLOW_CTX_EXECUTION_DATE=2021-11-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-18T00:00:00+00:00
[2021-11-19 10:41:49,409] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_for_Windows_7.7)
[2021-11-19 10:41:49,743] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 10:41:49,854] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 10:41:49,920] {transport.py:1819} INFO - Authentication (password) successful!
[2021-11-19 10:41:50,083] {sftp.py:158} INFO - [chan 0] Opened sftp connection (server version 3)
[2021-11-19 10:41:50,806] {sftp.py:158} INFO - [chan 0] sftp session closed.
[2021-11-19 10:41:50,806] {python.py:152} INFO - Done. Returned value was: None
[2021-11-19 10:41:50,830] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=Collection_resport, task_id=get_excel, execution_date=20211118T000000, start_date=20211119T051148, end_date=20211119T051150
[2021-11-19 10:41:50,913] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-19 10:41:50,973] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-19 10:41:58,809] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Collection_resport.get_excel manual__2021-11-19T05:10:57.878322+00:00 [queued]>
[2021-11-19 10:41:58,848] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Collection_resport.get_excel manual__2021-11-19T05:10:57.878322+00:00 [queued]>
[2021-11-19 10:41:58,848] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 10:41:58,848] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-19 10:41:58,848] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 10:41:58,872] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_excel> on 2021-11-19 05:10:57.878322+00:00
[2021-11-19 10:41:58,878] {standard_task_runner.py:52} INFO - Started process 13248 to run task
[2021-11-19 10:41:58,890] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Collection_resport', 'get_excel', 'manual__2021-11-19T05:10:57.878322+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/collection.py', '--cfg-path', '/tmp/tmpn1jtbq13', '--error-file', '/tmp/tmpgx0emi49']
[2021-11-19 10:41:58,895] {standard_task_runner.py:77} INFO - Job 71: Subtask get_excel
[2021-11-19 10:41:58,987] {logging_mixin.py:109} INFO - Running <TaskInstance: Collection_resport.get_excel manual__2021-11-19T05:10:57.878322+00:00 [running]> on host user-Latitude-3410
[2021-11-19 10:41:59,078] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=shindesushant818@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Collection_resport
AIRFLOW_CTX_TASK_ID=get_excel
AIRFLOW_CTX_EXECUTION_DATE=2021-11-19T05:10:57.878322+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-19T05:10:57.878322+00:00
[2021-11-19 10:41:59,189] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_for_Windows_7.7)
[2021-11-19 10:41:59,419] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 10:41:59,528] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 10:41:59,586] {transport.py:1819} INFO - Authentication (password) successful!
[2021-11-19 10:41:59,727] {sftp.py:158} INFO - [chan 0] Opened sftp connection (server version 3)
[2021-11-19 10:41:59,790] {sftp.py:158} INFO - [chan 0] sftp session closed.
[2021-11-19 10:41:59,791] {python.py:152} INFO - Done. Returned value was: None
[2021-11-19 10:41:59,818] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=Collection_resport, task_id=get_excel, execution_date=20211119T051057, start_date=20211119T051158, end_date=20211119T051159
[2021-11-19 10:41:59,859] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-19 10:41:59,930] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-19 10:57:01,293] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Collection_resport.get_excel manual__2021-11-19T05:26:49.866959+00:00 [queued]>
[2021-11-19 10:57:01,318] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Collection_resport.get_excel manual__2021-11-19T05:26:49.866959+00:00 [queued]>
[2021-11-19 10:57:01,319] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 10:57:01,319] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-19 10:57:01,319] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 10:57:01,358] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_excel> on 2021-11-19 05:26:49.866959+00:00
[2021-11-19 10:57:01,370] {standard_task_runner.py:52} INFO - Started process 31508 to run task
[2021-11-19 10:57:01,388] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Collection_resport', 'get_excel', 'manual__2021-11-19T05:26:49.866959+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/collection.py', '--cfg-path', '/tmp/tmp9n0oq0gw', '--error-file', '/tmp/tmpdm1hita5']
[2021-11-19 10:57:01,397] {standard_task_runner.py:77} INFO - Job 74: Subtask get_excel
[2021-11-19 10:57:01,664] {logging_mixin.py:109} INFO - Running <TaskInstance: Collection_resport.get_excel manual__2021-11-19T05:26:49.866959+00:00 [running]> on host user-Latitude-3410
[2021-11-19 10:57:02,078] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=shindesushant818@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Collection_resport
AIRFLOW_CTX_TASK_ID=get_excel
AIRFLOW_CTX_EXECUTION_DATE=2021-11-19T05:26:49.866959+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-19T05:26:49.866959+00:00
[2021-11-19 10:57:02,249] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_for_Windows_7.7)
[2021-11-19 10:57:02,675] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 10:57:02,834] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 10:57:03,534] {transport.py:1819} INFO - Authentication (password) successful!
[2021-11-19 10:57:03,640] {sftp.py:158} INFO - [chan 0] Opened sftp connection (server version 3)
[2021-11-19 10:57:04,403] {sftp.py:158} INFO - [chan 0] sftp session closed.
[2021-11-19 10:57:04,404] {python.py:152} INFO - Done. Returned value was: None
[2021-11-19 10:57:04,430] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=Collection_resport, task_id=get_excel, execution_date=20211119T052649, start_date=20211119T052701, end_date=20211119T052704
[2021-11-19 10:57:04,500] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-19 10:57:04,633] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-11-19 11:02:29,633] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Collection_resport.get_excel manual__2021-11-19T05:32:20.205855+00:00 [queued]>
[2021-11-19 11:02:29,665] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Collection_resport.get_excel manual__2021-11-19T05:32:20.205855+00:00 [queued]>
[2021-11-19 11:02:29,665] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 11:02:29,665] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-19 11:02:29,666] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 11:02:29,692] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_excel> on 2021-11-19 05:32:20.205855+00:00
[2021-11-19 11:02:29,697] {standard_task_runner.py:52} INFO - Started process 5397 to run task
[2021-11-19 11:02:29,701] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Collection_resport', 'get_excel', 'manual__2021-11-19T05:32:20.205855+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/collection.py', '--cfg-path', '/tmp/tmpi58_p26a', '--error-file', '/tmp/tmpbm_rxkzm']
[2021-11-19 11:02:29,711] {standard_task_runner.py:77} INFO - Job 77: Subtask get_excel
[2021-11-19 11:02:29,795] {logging_mixin.py:109} INFO - Running <TaskInstance: Collection_resport.get_excel manual__2021-11-19T05:32:20.205855+00:00 [running]> on host user-Latitude-3410
[2021-11-19 11:02:29,904] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=shindesushant818@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Collection_resport
AIRFLOW_CTX_TASK_ID=get_excel
AIRFLOW_CTX_EXECUTION_DATE=2021-11-19T05:32:20.205855+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-19T05:32:20.205855+00:00
[2021-11-19 11:02:30,029] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_for_Windows_7.7)
[2021-11-19 11:02:30,267] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 11:02:30,366] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 11:02:30,449] {transport.py:1819} INFO - Authentication (password) successful!
[2021-11-19 11:02:30,610] {sftp.py:158} INFO - [chan 0] Opened sftp connection (server version 3)
[2021-11-19 11:02:30,665] {sftp.py:158} INFO - [chan 0] sftp session closed.
[2021-11-19 11:02:30,666] {python.py:152} INFO - Done. Returned value was: None
[2021-11-19 11:02:30,686] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=Collection_resport, task_id=get_excel, execution_date=20211119T053220, start_date=20211119T053229, end_date=20211119T053230
[2021-11-19 11:02:30,721] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-19 11:02:30,806] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
